server: 
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/postions.yaml
client:
  url: http://loki:3100/api/prom/push
scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: syslog
        __path__: /var/log/syslog